language: python
python:
  - "3.6.10"
cache: pip
install:
  - pip install -r requirements.txt
  - pip install codecov
script:
  - pytest

# Push the results back to codecov
after_success:
  - codecov
