language: python
python:
  - "3.6.10"
cache: pip
install:
  - pip install -r requirements.txt
  - pip install codecov
  - pip install pytest==5.4.1
  - pip install pytest-cov==2.8.1
  - pip install pytest-xdist==1.31.0
script:
  - pytest

# Push the results back to codecov
after_success:
  - codecov
